# LangGraph Knowledge Graph System Configuration

# LLM Configuration
llm:
  default_model: "qwen3:4b"
  alternative_model: "mistral"
  
# Database Configuration
databases:
  neo4j:
    course_mapper:
      uri: "bolt://localhost:7687"
      auth: "none"
    kli_app:
      uri: "bolt://localhost:7688"
      auth: "none"
  elasticsearch:
    endpoint: "http://localhost:9200"
    index: "advanced_docs_elasticsearch_v2"
    vector_store_dir: "./elasticsearch_storage_v2"
    auth: "none"
  mongodb:
    content_preprocessor:
      uri: "mongodb://localhost:27017"
      database: "lmw_mvp_content_preprocessor"
      auth: "none"
    orchestrator_state:
      uri: "mongodb://localhost:27018"
      database: "lmw_mvp_orchestrator"
      auth: "none"
  postgresql:
    course_manager:
      host: "127.0.0.1"
      port: 5432
      database: "lmw_mvp_course_manager"
      user: "none"
      password: "none"
    query_strategy:
      host: "127.0.0.1"
      port: 5433
      database: "lmw_mvp_query_strategy"
      user: "none"
      password: "none"
    graph_query:
      host: "127.0.0.1"
      port: 5434
      database: "lmw_mvp_graph_query"
      user: "none"
      password: "none"
    learning_tree:
      host: "127.0.0.1"
      port: 5435
      database: "lmw_mvp_learning_tree"
      user: "none"
      password: "none"
    system_config:
      host: "127.0.0.1"
      port: 5436
      database: "lmw_mvp_system_config"
      user: "none"
      password: "none"
  redis:
    orchestrator_cache:
      host: "localhost"
      port: 6379
      db: 0
      auth: "none"

# Course Configuration
courses:
  default_course_id: "OSN"
  default_learner_id: "R000"

# Microservice Configuration
microservices:
  course_manager:
    enabled: true
    timeout: 300
  content_preprocessor:
    enabled: true
    chunk_size: 1000
    chunk_overlap: 100
  course_content_mapper:
    enabled: true
    agents: ["researcher", "lo_generator", "curator", "analyst", "kc_classifier"]
  kli_application:
    enabled: true
    agents: ["lp_identifier", "instruction_agent"]
  knowledge_graph_generator:
    enabled: true
    clear_existing: false
  query_strategy_manager:
    enabled: true
  graph_query_engine:
    enabled: true
  learning_tree_handler:
    enabled: true

# Faculty Approval Workflow
faculty_approval:
  stages:
    - "FACD"  # Faculty Approved Course Design
    - "FCCS"  # Faculty Confirmed Course Structure
    - "FFCS"  # Faculty Finalized Course Specification
  require_approval: true

# Paths
paths:
  prompts: "./prompts"
  data: "./data"
  uploads: "./uploads"
  logs: "./logs" 