# Database Configuration for LangGraph KG System
# DEPRECATED: This file is deprecated. Use database_connections.yaml instead.
# This file is kept for backward compatibility only.

# Please use config/database_connections.yaml for all database configuration.
# The database_connections.yaml file contains the complete and up-to-date
# configuration for all database connections in the system.

databases:
  neo4j:
    uri: "bolt://localhost:7687"
    username: "neo4j"
    password: "your_password"
    database: "neo4j"
    
  elasticsearch:
    host: "localhost"
    port: 9200
    scheme: "http"
    username: "elastic"  # optional
    password: "your_password"  # optional
    indices:
      course_content: "course_content"
      knowledge_components: "knowledge_components"
      
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "langgraph_kg"
    collections:
      learner_profiles: "learner_profiles"
      personalized_learning_trees: "personalized_learning_trees"
      learning_sessions: "learning_sessions"
      
  redis:
    host: "localhost"
    port: 6379
    password: null  # optional
    db: 0
    ttl:
      sessions: 3600  # 1 hour
      plt_cache: 86400  # 24 hours
      query_cache: 1800  # 30 minutes
